# Generated by Django 3.0.3 on 2020-03-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nop', models.PositiveIntegerField(default=0, verbose_name='板块人数')),
                ('noc', models.PositiveIntegerField(default=0, verbose_name='评论人数')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1, help_text='权重高者在前', verbose_name='权重')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PlateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.Plate', verbose_name='所属板块')),
            ],
            options={
                'verbose_name': '板块中的分类',
                'verbose_name_plural': '板块中的分类',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PlatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nov', models.PositiveIntegerField(default=0, verbose_name='访问人数')),
                ('noc', models.PositiveIntegerField(default=0, verbose_name='评论人数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.PlateCategory', verbose_name='所属分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持有者')),
            ],
            options={
                'verbose_name': '板块文章',
                'verbose_name_plural': '板块文章',
                'ordering': ['-created_time'],
            },
        ),
    ]
