# Generated by Django 3.0.3 on 2020-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platepost',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文章摘要'),
        ),
    ]
