# Generated by Django 3.0.3 on 2020-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('desc', models.CharField(max_length=500, verbose_name='简介')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否为主要')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='人数')),
            ],
            options={
                'verbose_name': '院系部门',
                'verbose_name_plural': '院系部门',
                'ordering': ['-created_time'],
            },
        ),
    ]
