# Generated by Django 3.0.3 on 2020-03-02 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nov', models.PositiveIntegerField(default=0, verbose_name='访问人数')),
                ('noc', models.PositiveIntegerField(default=0, verbose_name='评论人数')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持有者')),
                ('plate_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '板块文章',
                'verbose_name_plural': '板块文章',
                'ordering': ['-created_time'],
            },
        ),
    ]
